import type { Metadata } from "next";
import { Cairo, Montserrat } from "next/font/google";
import "@/app/[locale]/globals.css";
// import "react-toastify/dist/ReactToastify.css";

import Header from "@/components/custom/Header";
import Footer from "@/components/custom/Footer";
import { ToastContainer } from "react-toastify";
import Providers from "@/components/providers";

// const cairo = Cairo({ subsets: ["arabic"] });
// const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocalLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <Providers>
      {/* <html lang={locale} dir="rtl">
    <body className={`${cairo.className}`}> */}
      {/* all providers the app needed */}
      {/* header */}
      <Header />

      {/* main section */}
      <main className="relative flex min-h-[calc(100vh-210px)] flex-col items-center bg-zinc-100 dark:bg-black/30">
        {/* toaster container */}
        <ToastContainer stacked />

        {children}
      </main>
      {/* footer */}
      <Footer />
      {/* </body>
    </html> */}
    </Providers>
  );
}
